### ISSUE TITLE
Bug v.2.3.0 - Error undefined method `link_to_remote'

### ISSUE THREAD

**Issue by R-i-c-k-y** [teleological/redmine_stealth#26]
ActionView::Template::Error (undefined method `link_to_remote' for #<#<Class:0xc680734>:0xc682cc8>):
    20: <div id="wrapper2">
    21: <div id="wrapper3">
    22: <div id="top-menu">
    23:     <div id="account">
    24:         <%= render_menu :account_menu -%>
    25:     </div>
    26:     <%= content_tag('div', "#{l(:label_logged_as)} #{link_to_user(User.current, :format => :username)}".html_safe, :id => 'loggedas') if User.current.logged? %>
  lib/redmine/menu_manager.rb:102:in`render_menu_node'
  lib/redmine/menu_manager.rb:91:in `block in render_menu'
  lib/redmine/menu_manager.rb:168:in`block in menu_items_for'
  lib/redmine/menu_manager.rb:165:in `each'
  lib/redmine/menu_manager.rb:165:in`menu_items_for'
  lib/redmine/menu_manager.rb:90:in `render_menu'
  app/views/layouts/base.html.erb:23:in`_app_views_layouts_base_html_erb__677733586_105968000'

My (working) environment:

Environment:
  Redmine version                          2.3.0.stable
  Ruby version                             2.0.0 (i686-linux)
  Rails version                            3.2.13
  Environment                              production
  Database adapter                         Mysql2
Redmine plugins:
  advanced_roadmap                         0.8.0
  clipboard_image_paste                    1.6a
  due_date_reminder                        0.3.2
  extended_profile                         1.2.0
  google_analytics_plugin                  0.3.0-beta
  my_projects                              1.0
  openid_fix                               0.1.0
  project_overview                         1.1.0
  redmine_banner                           0.0.8
  redmine_documents_short                  0.1.0
  redmine_embedded_video                   0.0.3.1
  redmine_favorite_projects                1.0.0
  redmine_hide_estimated_hours             1.0.3
  redmine_hours                            0.1.0
  redmine_improved_searchbox               0.0.3
  redmine_information                      1.0.2
  redmine_inline_note_images_plugin        0.0.1
  redmine_issue_checklist                  2.0.5
  redmine_issue_extensions                 0.2.0
  redmine_issue_status_colors              0.0.1
  redmine_open_links_in_new_window         0.0.3
  redmine_plugin_views_revisions           0.0.1
  redmine_silencer                         0.2.0
  redmine_spent_time                       2.5.0
  redmine_tags                             2.0.1-dev
  redmine_theme_changer                    0.1.0
  redmine_work_time                        0.2.11
  redmine_xls_export                       0.2.1.t2
  sidebar_hide                             0.0.2
  wiking                                   0.0.3

**Comment by R-i-c-k-y** [comment]
up

**Comment by xadh00m** [comment]
Could you please check if this works for you (applied in latest version)?

https://github.com/teleological/redmine_stealth/issues/28

**Comment by R-i-c-k-y** [comment]
applied #27 and #28, but...
![error_](https://f.cloud.github.com/assets/432347/1051493/f837dfac-10cb-11e3-9248-f4eedf3dc7cf.png)
