### ISSUE TITLE
Not compatible with Redmine 3.1.1

### ISSUE THREAD

**Issue by min2sia** [teleological/redmine_stealth#34]
```
# bundle exec rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
TypeError: can't convert nil into String
/usr/share/redmine-3.1.1/plugins/redmine_stealth/init.rb:24:in `join'
/usr/share/redmine-3.1.1/plugins/redmine_stealth/init.rb:24:in `block in <top (required)>'
/usr/share/redmine-3.1.1/lib/redmine/plugin.rb:75:in `instance_eval'
/usr/share/redmine-3.1.1/lib/redmine/plugin.rb:75:in `register'
/usr/share/redmine-3.1.1/plugins/redmine_stealth/init.rb:19:in `<top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/usr/share/redmine-3.1.1/lib/redmine/plugin.rb:155:in `block in load'
/usr/share/redmine-3.1.1/lib/redmine/plugin.rb:146:in `each'
/usr/share/redmine-3.1.1/lib/redmine/plugin.rb:146:in `load'
/usr/share/redmine-3.1.1/config/initializers/30-redmine.rb:21:in `<top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/1.9.1/gems/railties-4.2.4/lib/rails/engine.rb:652:in `block in load_config_initializer'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/notifications.rb:166:in `instrument'
/var/lib/gems/1.9.1/gems/railties-4.2.4/lib/rails/engine.rb:651:in `load_config_initializer'
/var/lib/gems/1.9.1/gems/railties-4.2.4/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/var/lib/gems/1.9.1/gems/railties-4.2.4/lib/rails/engine.rb:615:in `each'
/var/lib/gems/1.9.1/gems/railties-4.2.4/lib/rails/engine.rb:615:in `block in <class:Engine>'
/var/lib/gems/1.9.1/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/1.9.1/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/1.9.1/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/lib/gems/1.9.1/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `each'
/var/lib/gems/1.9.1/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `tsort_each_child'
/var/lib/gems/1.9.1/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/1.9.1/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
/usr/share/redmine-3.1.1/config/environment.rb:14:in `<top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/1.9.1/gems/railties-4.2.4/lib/rails/application.rb:328:in `require_environment!'
/var/lib/gems/1.9.1/gems/railties-4.2.4/lib/rails/application.rb:457:in `block in run_tasks_blocks'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by HighwayStar** [comment]
I have this issue too with redmine 3.2.0

```
RAILS_ENV=production bundle exec rake db:migrate                
WARNING: Nokogiri was built against LibXML version 2.9.2, but has dynamically loaded 2.9.3
rake aborted!
TypeError: no implicit conversion of nil into String
/local/tomin/devel/redmine-3.2.0/plugins/redmine_stealth/init.rb:24:in `join'
/local/tomin/devel/redmine-3.2.0/plugins/redmine_stealth/init.rb:24:in `block in <top (required)>'
/local/tomin/devel/redmine-3.2.0/lib/redmine/plugin.rb:75:in `instance_eval'
/local/tomin/devel/redmine-3.2.0/lib/redmine/plugin.rb:75:in `register'
/local/tomin/devel/redmine-3.2.0/plugins/redmine_stealth/init.rb:19:in `<top (required)>'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/local/tomin/devel/redmine-3.2.0/lib/redmine/plugin.rb:155:in `block in load'
/local/tomin/devel/redmine-3.2.0/lib/redmine/plugin.rb:146:in `each'
/local/tomin/devel/redmine-3.2.0/lib/redmine/plugin.rb:146:in `load'
/local/tomin/devel/redmine-3.2.0/config/initializers/30-redmine.rb:21:in `<top (required)>'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/railties-4.2.5/lib/rails/engine.rb:652:in `block in load_config_initializer'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:166:in `instrument'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/railties-4.2.5/lib/rails/engine.rb:651:in `load_config_initializer'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/railties-4.2.5/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/railties-4.2.5/lib/rails/engine.rb:615:in `each'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/railties-4.2.5/lib/rails/engine.rb:615:in `block in <class:Engine>'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `each'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `tsort_each_child'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
/local/tomin/devel/redmine-3.2.0/config/environment.rb:14:in `<top (required)>'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/local/tomin/devel/redmine-3.2.0/plugins/redmine_digest/lib/tasks/digest.rake:32:in `<top (required)>'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/local/tomin/devel/redmine-3.2.0/lib/tasks/redmine.rake:186:in `block in <top (required)>'
/local/tomin/devel/redmine-3.2.0/lib/tasks/redmine.rake:186:in `each'
/local/tomin/devel/redmine-3.2.0/lib/tasks/redmine.rake:186:in `<top (required)>'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/railties-4.2.5/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/railties-4.2.5/lib/rails/engine.rb:658:in `each'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/railties-4.2.5/lib/rails/engine.rb:658:in `run_tasks_blocks'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/railties-4.2.5/lib/rails/application.rb:452:in `run_tasks_blocks'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/railties-4.2.5/lib/rails/engine.rb:453:in `load_tasks'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/railties-4.2.5/lib/rails/railtie.rb:194:in `public_send'
/local/tomin/devel/redmine-3.2.0/bundler/ruby/2.1.0/gems/railties-4.2.5/lib/rails/railtie.rb:194:in `method_missing'
/local/tomin/devel/redmine-3.2.0/Rakefile:7:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by HighwayStar** [comment]
Fix from #27 seems work

**Comment by HighwayStar** [comment]
as well as #30
