### ISSUE TITLE
Don't works with Redmine 5.0

### ISSUE THREAD

**Issue by pasqualedante** [teleological/redmine_stealth#37]
I have this issue on Redmine 5.0:

[ E 2022-06-01 13:00:42.5714 31605/Tb age/Cor/Con/CheckoutSession.cpp:283 ]: [Client 2-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 98ce9a0a. Please see earlier logs for details about the error.
App 31691 output: Error: The application encountered the following error: cannot load such file -- redmine_stealth (LoadError)
App 31691 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
App 31691 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
App 31691 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
App 31691 output: /opt/redmine/plugins/redmine_stealth/init.rb:37:in `<top (required)>'
App 31691 output: /opt/redmine/lib/redmine/plugin_loader.rb:31:in `load'
App 31691 output: /opt/redmine/lib/redmine/plugin_loader.rb:31:in `run_initializer'
App 31691 output: /opt/redmine/lib/redmine/plugin_loader.rb:108:in `each'
App 31691 output: /opt/redmine/lib/redmine/plugin_loader.rb:108:in `block in load'
App 31691 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:427:in `instance_exec'
App 31691 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:427:in `block in make_lambda'
App 31691 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
App 31691 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
App 31691 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:603:in `catch'
App 31691 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:603:in `block in default_terminator'
App 31691 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:199:in `block in halting'
App 31691 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `block in invoke_before'
App 31691 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `each'
App 31691 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `invoke_before'
App 31691 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:105:in `run_callbacks'
App 31691 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/reloader.rb:88:in `prepare!'
App 31691 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/railties-6.1.6/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
App 31691 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `instance_exec'
App 31691 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `run'
App 31691 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/railties-6.1.6/lib/rails/initializable.rb:61:in `block in run_initializers'
App 31691 output: /usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
App 31691 output: /usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
App 31691 output: /usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
App 31691 output: /usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
App 31691 output: /usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:347:in `each'
App 31691 output: /usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:347:in `call'
App 31691 output: /usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
App 31691 output: /usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
App 31691 output: /usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
App 31691 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/railties-6.1.6/lib/rails/initializable.rb:60:in `run_initializers'
App 31691 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/railties-6.1.6/lib/rails/application.rb:391:in `initialize!'
App 31691 output: /opt/redmine/config/environment.rb:16:in `<top (required)>'
App 31691 output: config.ru:3:in `require'
App 31691 output: config.ru:3:in `block in <main>'
App 31691 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
App 31691 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
App 31691 output: config.ru:1:in `new'
App 31691 output: config.ru:1:in `<main>'
App 31691 output: /usr/local/rvm/gems/ruby-3.0.0/gems/passenger-6.0.14/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 31691 output: /usr/local/rvm/gems/ruby-3.0.0/gems/passenger-6.0.14/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 31691 output: /usr/local/rvm/gems/ruby-3.0.0/gems/passenger-6.0.14/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 31691 output: /usr/local/rvm/gems/ruby-3.0.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:397:in `run_block_and_record_step_progress'
App 31691 output: /usr/local/rvm/gems/ruby-3.0.0/gems/passenger-6.0.14/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 31691 output: /usr/local/rvm/gems/ruby-3.0.0/gems/passenger-6.0.14/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 31691 output: /usr/local/rvm/gems/ruby-3.0.0/gems/passenger-6.0.14/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2022-06-01 13:00:50.3375 31605/Tk age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /opt/redmine: The application encountered the following error: cannot load such file -- redmine_stealth (LoadError)
Error ID: a620196c
Error details saved to: /tmp/passenger-error-5W44YK.html

**Comment by HighwayStar** [comment]
Fixed it in my own fork https://github.com/HighwayStar/redmine_stealth
